#!/usr/bin/expect
set 2fa [lindex $argv 0]
set loc [lindex $argv 1]
set auth [lindex $argv 2]
set timeout 5

spawn openvpn --config "$loc" --auth-user-pass "$auth"

expect "CHALLENGE: Enter 2FA Authenticato"
send  "$2fa\r"

expect "Initialization Sequence Completed"